#!/usr/bin/bash
# Backup a file with sequential numbering

# usage
if [ $# -gt 2 -o $# -lt 1 -o "$1" = "-h" -o "$1" = "--help" ] ; then
  echo "${0##*/} <file> <*dir> — backup a file with sequential numbering"
  exit 1
fi

# existence test for file and directory
[ ! -e "$1" ]             && echo "non-existent: "$1"" && non_exist=y
[ "$2" ] && [ ! -d "$2" ] && echo "non-existent: "$2"" && non_exist=y
[ "$non_exist" ] && exit 1

# source directory define
if [  ! "$2" ] ; then
  srcdir=.
else
  srcdir="${2%/}"
fi

# filename parsing: basename, noblename, extension
fbnm=${1##*/}
if [[ "$fbnm" = .* ]] ; then
  fnbl="${fbnm%_[0-9][0-9]*}"
  fext=""
else
  fnbl="${fbnm%.*}" ; fnbl="${fnbl%_[0-9][0-9]*}"
  fext=."${fbnm##*.}"
  [[ "$fext" = ."$fbnm" ]] && fext=""
fi

# previous file name parse number, calculate next
pfns=("$srcdir"/"$fnbl"_[0-9][0-9]*)
if [ ! -e "$pfns" ]; then
  fnum=00
else
  # previous file: name, basename, bnm extension-less, number; sequential number
  shopt -s nullglob
  pfnm="${pfns[-1]}"
  pbnm="${pfnm##*/}"
  pexl="${pbnm%.*}"
  pnum="${pexl: -2}"
  fnum=$(printf "%02u" $((10#$pnum + 1)))
fi

cp --archive --interactive --verbose "$1" "$srcdir"/"$fnbl"_"$fnum""$fext"
