#!/usr/bin/bash
# Backup a file with sequential numbering

# Usage
if [ $# -gt 2 -o $# -lt 1 -o "$1" = "-h" -o "$1" = "--help" ] ; then
  echo "${0##*/} <file> <*dir> — backup a file with sequential numbering"
  exit 1
fi

# Existence tests for file and directory
[ ! -e "$1" ]             && echo "non-existent: "$1"" && non_exist=y
[ "$2" ] && [ ! -d "$2" ] && echo "non-existent: "$2"" && non_exist=y
[ "$non_exist" ] && exit 1

# Source directory define and without trailing slash
[  ! "$2" ] && srcdir=.
srcdir="${srcdir%/}"

# Filename parsing: basename, noblename, extension
fbnm=${1##*/}
if [[ "$fbnm" = .* ]] ; then
  fnbl="${fbnm%_[0-9][0-9]*}"
  fext=""
else
  fnbl="${fbnm%.*}" ; fnbl="${fnbl%_[0-9][0-9]*}"
  fext=."${fbnm##*.}"
  [[ "$fext" = ."$fbnm" ]] && fext=""
fi

# Sequential number set or calculate from previous file
pnms=("$srcdir"/"$fnbl"_[0-9][0-9]*)
if [ ! -e "$pnms" ]; then
  fnum=00
else
  # Previous file: name, basename, bnm w/o ext., number; sequential number
  shopt -s nullglob
  pnme="${pnms[-1]}"
  pbnm="${pnme##*/}"
  pexl="${pbnm%.*}"
  pnum="${pexl: -2}"
  fnum=$(printf "%02u" $((10#$pnum + 1)))
fi

cp --archive --interactive --verbose "$1" "$srcdir"/"$fnbl"_"$fnum""$fext"
