#!/usr/bin/bash
# Copy file or stdin to X.org server clipboard.

# Required program test.
hash xclip 2>&- || { echo "Requires program: xclip."; error=y; }

# Regular user test.
if ! (( $EUID )); then
  echo "Requires regular user permissions."
  error=y
fi
[ "$error" ] && exit 1

# Usage.
usage () {
  echo "${0##*/} <*file> - copy a file or stdin to X.org server clipboard."
}
if [ $# -gt 1 -o "$1" = -h -o "$1" = --help ]; then
  usage
  exit 1
fi

# Stardard input or file existent test.
if ! [ -t 0 ]; then
  echo -n "$(< /dev/stdin)" | xclip -selection clipboard
  echo "Clipboard copied stdin."
elif [ -f "$1" ]; then
  xclip -in -selection clipboard "$1"
  echo "Cliboard copied file: "$1"."
else
  [ $# -eq 0 ] && { usage; exit 1; }
  echo "Non-existent: "$1"."
fi
