#!/usr/bin/bash
# Paste X.org server clipboard to file or stdout.

# Required program test.
hash xclip 2>&- || { echo "Requires program: xclip."; error=y; }

# Regular user test.
if ! (( $EUID )); then
  echo "Requires regular user permissions." 
  error=y
fi
[ "$error" ] && exit 1

# Usage.
if [ $# -gt 1 -o "$1" = -h -o "$1" = --help ]; then
  echo "${0##*/} <*file> - paste X.org server clipboard to file or stdout."
  exit 1
fi

# Output to stdout, if argument exists, to file.
if [ $# = 0 ]; then
 xclip -out -selection clipboard
elif [ -f "$1" ]; then
  read -p "File existent: "$1"; (e)xit, (a)ppend, (o)verwrite: " exists
  while true; do
    case $exists in
      [Ee] ) exit 1 ;;
      [Aa] ) xclip -out -selection clipboard >> "$1"
             echo "Clipboard output appended: "$1"."
             break 2;; 
      [Oo] ) xclip -out -selection clipboard >| "$1"                          
             echo "Clipboard output overwrote: "$1"."
             break 2;;
      *    ) echo "Answer: (e)xit, (a)ppend, (o)verwrite."
    esac
  done
else
  xclip -out -selection clipboard >| "$1"
  echo "Clipboard output newfile: "$1"."
fi
