#!/usr/bin/bash
# A wrapper script to decompress various archive types.

# option: help
if (( ! $# )) \
|| [[ "$*" =~ (^| )-h( |$) ]] || [[ "$*" =~ (^| )--help( |$) ]] \
|| [[ "$*" =  -l           ]] || [[ "$*" =  --list           ]] ; then
  printf "${0##*/} [*-l] <file>... — wrapper script to decompress various "
  echo   "archive types"
  echo   "  -l, --list  - list archive contents"
  exit 2
fi 

# option: list
[[ "$*" =~ (^| )-l( |$) ]] || [[ "$*" =~ (^| )--list( |$) ]] && list=yes

# archive existence test
for archive in "$@" ; do
  [ "$archive" = -l -o "$archive" = --list ] && continue
  [ ! -f "$archive" ] && { echo archive non-existent: "$archive" ;arc_noex=yes;}
done ; [ "$arc_noex" ] && exit 1

# program existence test
shopt -s extglob
for archive in "$@" ; do
[ "$archive" = -l -o "$archive" = --list ] && continue
case "$archive" in
  *.tar                    )  p=tar        ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.@(tar.bz2|tb@(2|z|z2)) )  p=bzip2      ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.@(tar.gz|tgz)          )  p=gzip       ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.tar.lz                 )  p=lzip       ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.@(tar.lzma|tlz)        )  p=xz         ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.@(tar.xz|txz)          )  p=xz         ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.@(tar.Z|t?(a)z)        )  p=gzip       ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.7z                     )  p=7zr        ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.bz2                    )  p=bunzip2    ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.exe                    )  p=cabextract ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.gz                     )  p=gunzip     ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.lz                     )  p=lzip       ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.rar                    )  p=unrar      ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.xz                     )  p=xz         ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.Z                      )  p=gzip       ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *.zip                    )  p=unzip      ; hash $p 2>&- \
                              || { echo program required: $p ; arc_prrq=y ; } ;;
  *                        )  { echo ext unknown: "$archive" ; arc_prrq=y ; } ;;
esac
done ; [ "$arc_prrq" ] && exit 1

# list
[ "$list" ] && for archive in "$@" ; do
[ "$archive" = -l -o "$archive" = --list ] && continue
echo -e "\e[1m "$archive" \e[0m"
case "$archive" in
  *.tar                    )  tar tvf           "$archive"      ;;  
  *.@(tar.bz2|tb@(2|z|z2)) )  tar tvf           "$archive"      ;;  
  *.@(tar.gz|tgz)          )  tar tvf           "$archive"      ;;  
  *.tar.lz                 )  tar tvf           "$archive"      ;;  
  *.@(tar.lzma|tlz)        )  tar tvf           "$archive"      ;;  
  *.@(tar.xz|txz)          )  tar tvf           "$archive"      ;;  
  *.@(tar.Z|t?(a)z)        )  tar tvf           "$archive"      ;;  
  *.7z                     )  7zr l             "$archive"      ;;  
  *.bz2                    )  echo              "${archive%.*}" ;;  
  *.exe                    )  cabextract --list "$archive"      ;;  
  *.gz                     )  echo              "${archive%.*}" ;;  
  *.lz                     )  echo              "${archive%.*}" ;;  
  *.rar                    )  unrar l           "$archive"      ;;  
  *.xz                     )  echo              "${archive%.*}" ;;    
  *.Z                      )  gzip --list       "$archive"      ;;  
  *.zip                    )  unzip -l          "$archive"      ;;  
esac
done ; [ "$list" ] && exit

# extract
for archive in "$@" ; do
case "$archive" in
  *.tar                    )  tar xf            "$archive"      ;;  
  *.@(tar.bz2|tb@(2|z|z2)) )  tar xf            "$archive"      ;;  
  *.@(tar.gz|tgz)          )  tar xf            "$archive"      ;;  
  *.tar.lz                 )  tar xf            "$archive"      ;;  
  *.@(tar.lzma|tlz)        )  tar xf            "$archive"      ;;  
  *.@(tar.xz|txz)          )  tar xf            "$archive"      ;;  
  *.@(tar.Z|t?(a)z)        )  tar xf            "$archive"      ;;  
  *.7z                     )  7zr x -bd         "$archive"      ;;  
  *.bz2                    )  bunzip2 --keep    "$archive"      ;;  
  *.exe                    )  cabextract        "$archive"      ;;  
  *.gz                     )  gunzip  --keep    "$archive"      ;;
  *.lz                     )  lzip    --keep    "$archive"      ;;
  *.rar                    )  unrar x           "$archive"      ;;  
  *.xz                     )  unxz    --keep    "$archive"      ;;
  *.Z                      )  gunzip  --keep    "$archive"      ;;  
  *.zip                    )  unzip   -q        "$archive"      ;;  
esac
done

