#!/usr/bin/bash
# (Alternate to rm.)  Move files to the trash rather than delete them.

trashdir=~/.local/share/Trash/files/

if [ ! -d "$trashdir" ]; then
  mkdir -p "$trashdir"
  echo "Trash directory created."
fi

mv --backup=existing --verbose --target-directory= "$trashdir" "$@"
