#!/usr/bin/bash
# A general downloader, a wrapper for curl.
#   -L : redirects follow
#   -O : filename is remote filename
#   -# : progress bar
#   -w : print filename when complete
#   -A : user agent
#   -C : resume download

for download in "$@"; do
  if [ -e "${download##*/}" ]; then  # resume attempt
    curl -L -O -# -w "\n%{filename_effective}" -A "Mozilla/4.0" -C - "$download"
  else
    curl -L -O -# -w "\n%{filename_effective}" -A "Mozilla/4.0"      "$download"
  fi
done
