#!/usr/bin/bash
# A generic linker

# Usage
if [ $# != 2 -o "$1" = -h -o "$1" = --help ] ; then
  echo "${0##*/} <source> <directory/linkname> — a generic linker"
  exit 1
fi

# Source absolute path resolution
if [ ! -e "$1" ]; then
  echo "Nonexist: "$1""
  exit 1
else
  source="$(realpath "$1")"
fi

# Directory absolute path resolution
if [ -e "$2" ] ; then
   if [ -d "$2" ] ; then
      link="$(realpath "$2")"
   else
      echo "Existent or non-dir.: "$2""
   fi
# Linkname absolute path resolution
else
   dirname="${2%/*}" ; [ "$2" = "$dirname" ] && dirname="."
   lnkname="${2##*/}"
   [ ! -d "$dirname" ] && { echo "Non-dir.: "$2"" ; exit 1 ; }
   link=""$(realpath "$dirname")"/"$lnkname""
fi

# Permission test
#if [ ! -w "$dirname" ] && hash sudo 2>&- ; then
#   sudo=sudo
#else
#   echo "Non-write-access, sudo not installed."
#   exit 1
#fi

ln -svi "$source" "$link" | awk -F ' -> ' '{ print $2 " -> " $1 }' |      GREP_COLOR='1;36' grep --color=always " ‘.*$"
