#!/usr/bin/bash
# A generic linker

# Usage
if [ $# != 2 -o "$1" = -h -o "$1" = --help ] ; then
  echo "${0##*/} <source> <directory,linkname> — a generic linker"
  exit 1
fi

# Source absolute path resolution
if [ ! -e "$1" ]; then
  echo "Nonexist: "$1""
  exit 1
else
  if [ -d "$1" ] ; then
     cd "$1"
     srcname="$(pwd)"
  else
     dirname="${1%/*}" ; [ "$1" = "$dirname" ] && dirname="."
     bsename="${1##*/}"
     cd "$dirname"
     srcname="$(pwd)"/"$bsename" 
  fi
fi

# Directory absolute path resolution
if [ -e "$2" ] ; then
   if [ -d "$2" ] ; then
      cd "$2"
      lnkname="$(pwd)"
   else
      echo "Existent or non-dir.: "$2""
      exit 1
   fi
# Linkname absolute path resolution
else
   dirname="${2%/*}" ; [ "$2" = "$dirname" ] && dirname="."
   bsename="${2##*/}"
   [ ! -d "$dirname" ] && { echo "Non-dir.: "$2"" ; exit 1 ; }
   cd "$dirname"
   lnkname="$(pwd)"/"$bsename"
fi

ln -svi "$srcname" "$lnkname" | awk -F ' -> ' '{ print $2 " -> " $1 }' |      GREP_COLOR='1;36' grep --color=always " ‘.*$"
