#!/usr/bin/bash
# Archive files - a basic wrapper script to simplify the task.

# help
if [ $# -eq 0 -o "$1" = -h -o "$1" = --help ] ; then
  echo "${0##*/} <file1> <*dir>... - archive files, folders..."
  exit 2
fi

# file existence test
for file in "$@" ; do
  [ ! -e "$file" ] && echo "file non-existent: "$file"." && error=y
done
[ "$error" ] && exit 1

# archive name
read -p "Name archive with extension [archive.tar.gz]: " archive_name 
[ ! "$archive_name" ] && archive_name=archive.tar.gz

# archive existence test
if [ -f "$archive_name" ] ; then
  echo "archive existent: "$archive_name""
  exit 1
fi

# archive creation
tar --create --auto-compress --file "$archive_name" "$@" && \
  [ -f "$archive_name" ] && echo "archive created: "$archive_name""
