#!/usr/bin/bash
# Power management tasks.

# Usage.
usage () {
    echo -n "${0##*/} [--poweroff,-p] [--restart,-r] [--suspend,-s] "
    echo    "[--hibernate,-h] [--blank,-b]"
}; [ $# -ne 1 -o "$1" = --help ] && { usage; exit; }

# Root test; admin. program set.
if (( $EUID )); then
  hash sudo 2>&- || { echo "Requires program: sudo."; exit 1; }
  sudo=sudo
fi

case $1 in
  --poweroff  | -p )
    echo "Shutting Down..."
    $sudo systemctl poweroff                                                  ;;
  --reboot    | -r )
    echo "Restarting System..."
    $sudo systemctl reboot                                                    ;;
  --suspend   | -s )
    echo "Suspending to RAM..."
    $sudo systemctl suspend                                                   ;;
  --hibernate | -h )
    echo "Hibernating to Disk..."
    $sudo systemctl hibernate                                                 ;;
  --blank     | -b )
    echo "Sleeping Monitor..."
    sleep 1 && xset s activate                                                ;;
  * )
    usage ; exit 1
esac
