#!/usr/bin/bash
# Terminal colors print
# others terminal-color scripts: http://tinyurl.com/k33uukx
# terminal colors and hex codes: http://tinyurl.com/2pms95

# System colors
echo "System colors:"
for i in {00..07}; do
  printf "\e[48;5;${i}m$i    "
done; echo -e "\e[0m"

for i in {08..15}; do
  printf "\e[48;5;${i}m$i    "
done; echo -e "\e[0m"
echo

# Color cube 6x6
echo "8 bit color cube:"
for i in {16..231}; do
    echo -en "\e[48;5;${i}m$i\t"
    [ $((++j%6)) -eq 0 ] && echo -e "\e[0m"
done
echo

# Grayscale
echo "Grayscale:"
for i in {232..243}; do printf "\e[48;5;${i}m$i "; done; echo -e "\e[0m"
for i in {244..255}; do printf "\e[48;5;${i}m$i "; done; echo -e "\e[0m\n"
