#!/usr/bin/bash
# Trash files rather than remove/delete them (rm alternate)

# Usage
[ "$1" = -h -o "$1" = --help ] || [[ -z "$@" ]] && \
  { echo "${0##*/} — trash files rather than remove/delete them (rm alternate)" ; exit 1 ; }

# File existence test
for f in "$@"; do
  [ ! -e "$f" ] && { echo "Non-existent file: "$f"" ; nonexist=true ; }
done
[ "$nonexist" ] && exit 1

trashdir=~/.local/share/Trash/files/
[ ! -d "$trashdir" ] && { mkdir -p "$trashdir" && \
  echo "Trash directory created" ; }

for f in "$@" ; do
  mv --backup=existing --verbose --target-directory "$trashdir" "$f"
done
