#!/usr/bin/bash
# General archive extractor.

# Usage display if no parameters given
if [[ -z "$@" ]]; then
  echo "${0##*/} [archive] - general archive extractor"
  exit
fi

# Test if file(s) exists
for f in $@; do
  if [ ! -f "$f" ]; then
    echo "File non-exist: "$f"" && file_non=true
  fi; done
  [ "$file_non" = true ] && exit 1

# Extract file by using extension as reference to type
for a in $@; do
  case "$a" in
    *.7z      ) bsdtar xvf  "$a"                ;;
    *.bz2     ) bsdtar xvf  "$a"                ;;
    *.tar.bz2 ) bsdtar xvf  "$a"                ;;
    *.tbz2    ) bsdtar xvf  "$a"                ;;
    *.deb     ) ar vx       "$a"                ;;
    *.gz      ) bsdtar xvf  "$a"                ;;
    *.tar.gz  ) bsdtar xvf  "$a"                ;;
    *.tgz     ) bsdtar xvf "$a"                 ;;
    *.tar     ) bsdtar xvf  "$a"                ;;
    *.tar.xz  ) bsdtar xvf  "$a"                ;;
    *.txz     ) bsdtar xvf  "$a"                ;;
    *.rar     ) bsdtar xvf  "$a"                ;;
    *.zip     ) bsdtar xvf  "$a"                ;;
    *.Z       ) uncompress  "$a"                ;;
    *         ) echo "Unsupported file format"  ;;
  esac
done
