#!/usr/bin/bash
# Words sort in alphabetical order

# Usage
if [ $# -eq 0 -a -t 0 ] || [ "$1" = -h -o "$1" = --help ] ; then
  echo "<*stdin> ${0##*/} <*file> <*word1 word2…> — words sort in alphabetical order"
  exit
fi

if   [ ! -t 0 ] ; then
  echo "$(< /dev/stdin)" | tr " " "\n" | sort -uVf | tr "\n" " "
elif [ -f "$1" ]; then
  cat "$1"               | tr " " "\n" | sort -uVf | tr "\n" " "
else
  echo "$@"              | tr " " "\n" | sort -uVf | tr "\n" " "
fi
